# Example joint states for a 6-DOF robot, in degrees.
# Each inner list is a joint configuration: [j1, j2, j3, j4, j5, j6]
joint_states_degrees:
  - [-70, -15, -20, 0, 0, 0]
  - [-75, -10, -10, 0, 0, 0]
  - [-65, -20, -20, 0, 0, 0]
  # Add more diverse poses for good calibration
